### ISSUE TITLE
【功能请求】超时未操作，自动关闭选台界面

### ISSUE THREAD

**Issue by yaoxieyoulei** [yaoxieyoulei/mytv-android#1]
### 功能描述
超时未操作，自动关闭选台界面

**Comment by silverzhaojr** [comment]
在最新版本 1.3.0 中，通过 OK 键打开频道选台界面时，似乎不会自动关闭了。等了十几秒还一直停留显示着。

**Comment by yaoxieyoulei** [comment]
加了弹窗后页面层级变复杂了，不太好监听用户操作，所以暂时屏蔽了

**Comment by yaoxieyoulei** [comment]
添加该功能后，性能影响严重，暂时屏蔽
