### ISSUE TITLE
2.2.0 应用权限

### ISSUE THREAD

**Issue by newer15** [yaoxieyoulei/mytv-android#101]
MYTV存储权限必须打开,不然直播源加载本地失败。

![t2](https://github.com/user-attachments/assets/5fad623d-ebf1-4933-a4c7-febaad91ea6a)

**Comment by liqiangsky** [comment]
> 存储权限必须打开,不然本地直播源上传失败。
> 
> ![t2](https://private-user-images.githubusercontent.com/48373190/358855592-5fad623d-ebf1-4933-a4c7-febaad91ea6a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NDI2MzQsIm5iZiI6MTcyMzk0MjMzNCwicGF0aCI6Ii80ODM3MzE5MC8zNTg4NTU1OTItNWZhZDYyM2QtZWJmMS00OTMzLWE0YzctZmViYWFkOTFlYTZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDAwNTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOTgwYWZhNmUxMmQxN2UyYTZlZjkwZjBjZDhmM2JmNmRmNmQ5NWNiNGIzYzI0ZjhhMWNiNTgxNjIwYjBlYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1wwps-vC-RzsRe9aIqRzXiPdPilQEraZJMhPpMLgt0g)

那你就给权限啊

**Comment by newer15** [comment]
怎么给,你试过沒有?

**Comment by liqiangsky** [comment]
> 怎么给,你试过沒有?

没有，我都是传到github上

**Comment by newer15** [comment]
![t3](https://github.com/user-attachments/assets/03ad5cce-0f8f-40d1-a9dd-b0c11cf5e1b6)

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.2.1

**Comment by newer15** [comment]
在模拟器上可以用了android9,但在android tv10上还是不行。
![Screenshot](https://github.com/user-attachments/assets/8920ee98-a730-46d7-a6de-3f7ddd9cf846)

**Comment by newer15** [comment]
Exception 'open failed: EACCES (Permission denied)'

https://stackoverflow.com/questions/8854359/exception-open-failed-eacces-permission-denied-on-android
