### ISSUE TITLE
2.2.0非调试状态下换台导致解码器切换时，会黑屏只有声音

### ISSUE THREAD

**Issue by HuaHuaY** [yaoxieyoulei/mytv-android#102]
### 问题描述
设备是TCL 55Q9K，用默认的直播源，cctv9用的解码器是OMX.MS.AVC.Decoder，cctv10是OMX.MS.HEVC.Decoder。如果不在设置里打开调试中的显示FPS或者显示播放器信息，在这两个台之间切换就会黑屏，只有声音。如果打开任何一个调试，就不会黑屏。2.1.2没有这个问题。

以前用1.几版本也遇到过这种情况，但忘记当时用的版本号了。

### 复现步骤
在cctv9和10之间切换

### 预期行为
不黑屏，正常显示画面

### 系统信息
TCL 55Q9K，系统版本V8-T653T11-LF1V220.001895

**Comment by iamiwa** [comment]
我也有这个问题，上个版本不会黑屏

**Comment by 5918vo** [comment]
同 tcl 切换会黑屏

**Comment by yaoxieyoulei** [comment]
试试 https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.2.1

**Comment by HuaHuaY** [comment]
> 试试 https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.2.1

已修复
