### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Yscliking** [yaoxieyoulei/mytv-android#107]
### 问题描述
电视直播打开网络io错误。

### 复现步骤
下载mytv-android-tv-2.2.0-all-sdk21.apk安装包
打开任意一个频道显示io错误

### 预期行为
正常播放

**Comment by yaoxieyoulei** [comment]
网络不支持ipv6

**Comment by Yao-Xiao-Chun** [comment]
使用的时候，可以先测试一下支持ipv6，https://test-ipv6.com/ 可以用这个地址测试
