### ISSUE TITLE
问题反馈 你们晚上 8-10点ipv6的频道卡吗

### ISSUE THREAD

**Issue by zhangsj** [yaoxieyoulei/mytv-android#108]
### 问题描述
晚上ipv6的频道下载不到200 K ，v4正常看。 在电脑上ipv6测速也正常

### 预期行为
需要自己添加一些源吗？还是如何修复

**Comment by 5918vo** [comment]
卡

**Comment by zyd16888** [comment]
自己找几个源填进去，最好找你当地运营商的源

**Comment by yanxianchao** [comment]
> 自己找几个源填进去，最好找你当地运营商的源

去哪里可以找本地运营商的源？

**Comment by yaoxieyoulei** [comment]
直播源问题
