### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by 951189695** [yaoxieyoulei/mytv-android#110]
你好作者 问一下 io network 连接失败。是因为ipv6的问题嘛？因为我启用混合模式能播放。但是之前都能连上啊。路由器v6也是打开的。不知道为啥就不行了，全是网络连接失败。

**Comment by yaoxieyoulei** [comment]
测试下ipv6：https://test-ipv6.com/index.html.zh_CN
或者换个直播源：https://tv.iill.top/m3u/Gather
