### ISSUE TITLE
能不能支持老盒子系统4.4呢

### ISSUE THREAD

**Issue by xuanwumen** [yaoxieyoulei/mytv-android#111]
能不能支持老盒子系统4.4呢

**Comment by WenMoshi** [comment]
+1，强烈建议并附议。确实，安卓4.4还是有很多设备在服役，没有任何问题，把SDK、API降到19，就是给旧设备带来福音。

**Comment by canronglan** [comment]
移动魔百盒用户，升级到5.1.1，apk显示解析失败
