### ISSUE TITLE
能否创建个QQ群，方便沟通

### ISSUE THREAD

**Issue by wyt990** [yaoxieyoulei/mytv-android#113]
### 功能描述
请提供对所请求功能的清晰描述。
Telegram: https://t.me/mytv_android，我这里安装了，也连不上网络，所以能否建个QQ群？
### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by yaoxieyoulei** [comment]
<img src="https://github.com/user-attachments/assets/fc39cc3d-79db-4cfc-806e-f1fdfc31ea2f" width="48%"/>
