### ISSUE TITLE
在谷歌TV（Chromecast)成功安装，但是有BUG，请修正

### ISSUE THREAD

**Issue by chengbj522** [yaoxieyoulei/mytv-android#116]
在谷歌TV安装了此软件，好多频道无法播放，就算能播放的也要好几秒钟甚至更长时间的延迟，不知是不是在缓存，有如下画面截图
![PXL_20240905_091938579 MP](https://github.com/user-attachments/assets/cf40ead9-b1e8-46e4-a53d-42a8b92070dd)
另外目前的软件在切换电视台的时候明显卡顿一下再播放。

**Comment by yaoxieyoulei** [comment]
看看是否支持ipv6，https://ipw.cn/

**Comment by chengbj522** [comment]
家里的宽带已经开通了ipv6,而我装到另外一台Android 电视就没有这个问题，这个谷歌TV电视盒子就不行

**Comment by yaoxieyoulei** [comment]
把混合模式关掉

**Comment by chengbj522** [comment]
不是混合模式的问题，已经尝试过了
