### ISSUE TITLE
打开VPN代理无法观看

### ISSUE THREAD

**Issue by wrb233** [yaoxieyoulei/mytv-android#118]
### 问题描述
打开VPN无法观看

### 相关截图或日志
![17260561570118041646751807073426](https://github.com/user-attachments/assets/44deea20-fbb0-4300-9639-dd82c6d4d2c3)

**Comment by liqiangsky** [comment]
这是你网络不好吧

> ### 问题描述
> 打开VPN无法观看
> 
> ### 相关截图或日志
> ![17260561570118041646751807073426](https://private-user-images.githubusercontent.com/23077127/366447077-44deea20-fbb0-4300-9639-dd82c6d4d2c3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDIzNzIsIm5iZiI6MTcyNjEwMjA3MiwicGF0aCI6Ii8yMzA3NzEyNy8zNjY0NDcwNzctNDRkZWVhMjAtZmJiMC00MzAwLTk2MzktZGQ4MmM2ZDRkMmMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAwNDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZWMzODU1NDAxM2NlYWRlOGY0MDAzYjNjNmNhYmMzMjIwYzAyYjk3MDgzNjhiMjc5Y2Q1NDI5MTM5MTQ5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ptTJx2hShk5DuGPANt0oQOfqdPduPeeH9jJO_bf5BhE)
