### ISSUE TITLE
电信的rtsp源播放黑屏无声音

### ISSUE THREAD

**Issue by vbskycn** [yaoxieyoulei/mytv-android#121]
电信的rtsp源播放黑屏无声音
rtsp://115.153.254.81/PLTV/88888888/224/3221225699/iptv8040.smil
只能在本地电信的网络上面播放

源在其他播放器上面播放正常，有效的

是不是解码器的原因
![image](https://github.com/user-attachments/assets/9c913bf0-f621-458e-8a81-9de17aef70d4)

**Comment by yaoxieyoulei** [comment]
不支持rtsp

**Comment by KaguraRinko** [comment]
> 电信的rtsp源播放黑屏无声音 rtsp://115.153.254.81/PLTV/88888888/224/3221225699/iptv8040.smil 只能在本地电信的网络上面播放
> 
> 源在其他播放器上面播放正常，有效的
> 
> 是不是解码器的原因 ![image](https://private-user-images.githubusercontent.com/34542650/367484711-9c913bf0-f621-458e-8a81-9de17aef70d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTM3NjksIm5iZiI6MTcyNjY1MzQ2OSwicGF0aCI6Ii8zNDU0MjY1MC8zNjc0ODQ3MTEtOWM5MTNiZjAtZjYyMS00NThlLThhODEtOWRlMTdhZWY3MGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA5NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MThiN2JmY2M5Y2IxNjlhN2NmOGVmNjY4YWUyMjViZTMzYjY0MzliNDBmNzcxNzQwNGNlYjU0ZWJhMmY3OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHjhnruauMnMZSSIhqElFnMZ4tMuOnrb-jIbDVvbJas)

电信 IPTV 单播相关问题可以看这个
#105
