### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by unique2072** [yaoxieyoulei/mytv-android#128]
### 问题描述
手机上使用移动网络播放正常，但是连接wifi时显示播放失败，代码2001

### 系统信息
安卓手机

**Comment by yaoxieyoulei** [comment]
不支持ipv6

**Comment by unique2072** [comment]
> 不支持ipv6

是的，我刚刚检查了一下，我的网络确实只支持ipv4。这一点有办法解决吗？我切换直播源，里面有一项备注ipv4/ipv6,但还是不行。

**Comment by yaoxieyoulei** [comment]
只能自己找其他直播源

**Comment by ejiandan** [comment]
我测试了下，网络肯定是支持IPV6的，电脑上正常，手机Wi-Fi连接，无法播放，2001

**Comment by ejiandan** [comment]
搞好了，手机没问题，我网络设置的问题。播放正常。
