### ISSUE TITLE
问题反馈推送播放源文件出错

### ISSUE THREAD

**Issue by Robertoyang-droid** [yaoxieyoulei/mytv-android#136]
### 问题描述
请提供一个清晰而简明的问题描述。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by Robertoyang-droid** [comment]
这是加载后出现的错误消息
加载失败
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https'
but no scheme was found for /stora...

**Comment by yaoxieyoulei** [comment]
文件路径错了，或没权限

**Comment by Robertoyang-droid** [comment]
路径应该没有错，如果没有权限，应该怎么操作？请指教。多谢！

**Comment by shuangmianxiaoQ** [comment]
> 路径应该没有错，如果没有权限，应该怎么操作？请指教。多谢！

/storage/emulated/xxx.m3u，试试
