### ISSUE TITLE
TV使用问题汇总

### ISSUE THREAD

**Issue by lskyzero** [yaoxieyoulei/mytv-android#145]
### 问题描述
1.最严重bug，进入app后自动更新远程节目单后，提示获取失败，然后按菜单键进入设置页面后（设置一通后），无法退回直播界面，只能按两次返回键退出app重新进入
2.能否将默认远程直播源添加一个删除按钮，不然每次进入都是重新更新远程直播源节目，很多人这几个ipv6的远程源更新不了的，每次失败都占用很多时间
3.静态推送推送完后没有反应，推送文件也添加不了，最后用静态推送，推送完也不能正常更新节目
4.播放器UA如何更换别的播放器内核？还是只有EXO内核？

### 系统信息
2.2.3

**Comment by jw8013** [comment]
安卓4.4的电视，好像会内存泄漏，断开电源开机可以看，息屏再开就有声音，没画面，退出就开始卡死
