### ISSUE TITLE
RTSP无法播放

### ISSUE THREAD

**Issue by zzzz0317** [yaoxieyoulei/mytv-android#147]
https://github.com/yaoxieyoulei/mytv-android/blob/d8e7e6f05abae11ec2759cfebe117aeeeb374872/app/src/main/java/top/yogiczy/mytv/ui/screens/leanback/video/player/Media3VideoPlayer.kt#L110C1-L111C1

这里是否应为 CONTENT_TYPE_RTSP？
不过改了之后好像还是无法播放，同一个源（obs-rtspserver）VLC可以播放
错误代码是 LOAD_TIMEOUT(10003)

**Comment by zzzz0317** [comment]
https://github.com/yaoxieyoulei/mytv-android/issues/105

**Comment by yaoxieyoulei** [comment]
不支持rtsp
