### ISSUE TITLE
问题反馈 IPV6源画面闪

### ISSUE THREAD

**Issue by flowiceeos** [yaoxieyoulei/mytv-android#150]
2.2.3版播放IPV6源画面会闪，1.4.4版没这个问题。

**Comment by dfy167** [comment]
一样

**Comment by HK7009** [comment]
不是IPv6的问题IPv4也闪

**Comment by FRANKASEE** [comment]
用2.2.0版本

**Comment by FRANKASEE** [comment]
其他的版本都有问题

**Comment by yaoxieyoulei** [comment]
请尝试 https://github.com/yaoxieyoulei/mytv-android/releases/download/tv2.2.5/o-low-media3-mytv-android-tv-2.2.5-all-sdk21.apk

**Comment by wjw020206** [comment]
> 请尝试 https://github.com/yaoxieyoulei/mytv-android/releases/download/tv2.2.5/o-low-media3-mytv-android-tv-2.2.5-all-sdk21.apk

我也遇到这个问题，实测在电视上 2.2.5 版本播放 IPV6 源画面依旧存在这个问题，刚开始播放正常，但是放有一会儿就会出现闪烁的问题

**Comment by yaoxieyoulei** [comment]
尝试 https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.2.7
