### ISSUE TITLE
直播源的切换不太方便

### ISSUE THREAD

**Issue by tuutoo** [yaoxieyoulei/mytv-android#152]
### 功能描述
请提供对所请求功能的清晰描述。
希望可以方便的切换直播源，现在要跑到设置，再选好几个选项，另外还需要重启 app

### 目标
请描述你希望通过这个功能实现的目标。
在有多个直播源的时候，希望可以更方便的切换直播源。并且不需要重启 app。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用
IPTV pro

**Comment by kilvn** [comment]
切换了得杀进程，硬重启app

**Comment by tuutoo** [comment]
> 切换了得杀进程，硬重启app

是啊  点到切换直播源就要点好几次按钮。然后再退出，再重进。如果能再简单一点就好了。
