### ISSUE TITLE
最低支持的安卓版本是多少

### ISSUE THREAD

**Issue by dotaqi** [yaoxieyoulei/mytv-android#161]
### 功能描述
请提供对所请求功能的清晰描述。
我有2个盒子，一个移动盒子安卓4，一个当贝盒子安卓5 都不兼容
### 目标
请描述你希望通过这个功能实现的目标。
能否做下适配
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by Alonewader** [comment]
亲测原生安卓4流畅可用！
