### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by iswon** [yaoxieyoulei/mytv-android#165]
### 问题描述
比如cctv1，在正常观看，突然黑屏，又突然回来正常，无规律的反复。

起初我以为是自动切换直播源，于是就换成单源订阅地址（自用源），还是出现上述情况

很影响看电视，特别是体育频道，

### 复现步骤
每次观看都重复出现

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
海信 65E8K

### 相关截图或日志
时间短，无法截屏

**Comment by yaoxieyoulei** [comment]
无法复现
