### ISSUE TITLE
凤凰卫视

### ISSUE THREAD

**Issue by baijin4422** [yaoxieyoulei/mytv-android#167]
凤凰卫视一卡一卡的。

**Comment by lishengwei** [comment]
这种一般都是网络环境访问直播源的问题，软件估计是不会帮助解决的。需要自己找自己环境能够稳定播放的直播源。

**Comment by baijin4422** [comment]
我试过了，手机上网中国移动、中国联通、路由器的宽带都不行，看凤凰卫视都一卡一卡的，其他台没事，OurTV软件看凤凰卫视就没事。有什么办法吗？

---原始邮件---
发件人: "Shengwei ***@***.***&gt;
发送时间: 2024年10月11日(周五) 下午4:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yaoxieyoulei/mytv-android] 凤凰卫视 (Issue #167)




 
这种一般都是网络环境访问直播源的问题，软件估计是不会帮助解决的。需要自己找自己环境能够稳定播放的直播源。
