### ISSUE TITLE
fanmingming直播源cctv2无法播放，请解决，非常感谢！

### ISSUE THREAD

**Issue by chtywzy** [yaoxieyoulei/mytv-android#169]

**Comment by whybm** [comment]
fanmingming直播源cctv2地址和其他频道不一样，可能是这个原因无法播放，但是用其他壳子能播放，希望能修复

**Comment by zhuweijia** [comment]
+1 也是遇到相同的问题，希望可以debug下，修复下
附上具体的m3u链接：http://[2409:8087:74f0:22::4]:6410/270000001128/9900000502/index.m3u8?

**Comment by Dachongzi8** [comment]
播放失败
ERROR_CODE_IO_BAD_HTTP_STATUS(2004)

**Comment by LiteCoder** [comment]
1.44版本cctv2也是播放失败

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.2.5
