### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by jow905** [yaoxieyoulei/mytv-android#17]
### 问题描述
切换到无法播放的电台时，软件崩溃退出，
重开软件时因默认播放上次选择的电台，又导致软件退出，无法正常使用。

### 复现步骤
切换到国外电台， 比如: BBC

### 预期行为
希望能提示无法播放，而不是直接退出软件

### 系统信息
小米电视。

**Comment by iodata999** [comment]
很喜欢作者的极简播放器，也提几个改进功能，
1。应用加载时自动更新/刷新直播源，因为现在直播源失效太快了，一天中线路失效很多个，缓冲后每次多要手动刷新。
2。播放中直播源断流后会一直卡死，希望能自动跳转另外线路
3。精简下设置，比如更新/直播源缓冲什么的

**Comment by yaoxieyoulei** [comment]
> 1。应用加载时自动更新/刷新直播源，因为现在直播源失效太快了，一天中线路失效很多个，缓冲后每次多要手

可以到更多设置中，改一下缓存时间

**Comment by yaoxieyoulei** [comment]
> ### 问题描述
> 切换到无法播放的电台时，软件崩溃退出，
> 重开软件时因默认播放上次选择的电台，又导致软件退出，无法正常使用。
> 
> ### 复现步骤
> 切换到国外电台， 比如: BBC
> 
> ### 预期行为
> 希望能提示无法播放，而不是直接退出软件
> 
> ### 系统信息
> 小米电视。
> 

测试出来是不支持的直播源格式导致的崩溃，比如rtsp之类的
