### ISSUE TITLE
关于2.2.4的画质分辨率显示

### ISSUE THREAD

**Issue by sakana164** [yaoxieyoulei/mytv-android#173]
### 功能描述
请提供对所请求功能的清晰描述。
为什么新版本把源分辨率显示统一改成了FHD，显示FHD没有办法获取源分辨率了，感觉还是显示具体分辨率更直观一点
### 目标
请描述你希望通过这个功能实现的目标。
显示源分辨率
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。
改回显示分辨率或者设置中加入开关可以切换
### 其他
请提供已实现该功能或类似功能的应用

**Comment by yaoxieyoulei** [comment]
对应关系

240 -> "240p"
360 -> "360p"
480 -> "480p"
720 -> "HD"
1080 -> "FHD"
1440 -> "QHD"
2160 -> "4K UHD"
4320 -> "8K UHD"
