### ISSUE TITLE
问题反馈CCTV2播放失败

### ISSUE THREAD

**Issue by zhascg** [yaoxieyoulei/mytv-android#177]
### 问题描述
CCTV唯独2台播放失败，其他台都正常。
1.4.4、2.2.3、2.2.4，盒子、平板和手机都一样。

**Comment by yan-sheng-li** [comment]
我CCTV都不行

**Comment by Dachongzi8** [comment]
播放失败
ERROR_CODE_IO_BAD_HTTP_STATUS(2004)

**Comment by ducdieu** [comment]
是APP自带的播放器，要换成 ijkplayer，这个在 3.1.0 版开始有。
只分享在Telegram群组里

**Comment by zhascg** [comment]
> 是APP自带的播放器，要换成 ijkplayer，这个在 3.1.0 版开始有。 只分享在Telegram群组里

这。。小飞机在哪里？

**Comment by ducdieu** [comment]
> > 是APP自带的播放器，要换成 ijkplayer，这个在 3.1.0 版开始有。 只分享在Telegram群组里
> 
> 这。。小飞机在哪里？

不是在mytv-android主页面就有吗？拉到最下面。。。

**Comment by zhascg** [comment]
> > > 是APP自带的播放器，要换成 ijkplayer，这个在 3.1.0 版开始有。 只分享在Telegram群组里
> > 
> > 
> > 这。。小飞机在哪里？
> 
> 不是在mytv-android主页面就有吗？拉到最下面。。。

嗯嗯，已经在群里了。

**Comment by wflmy** [comment]
> ### 问题描述
> CCTV唯独2台播放失败，其他台都正常。1.4.4、2.2.3、2.2.4 ，盒子、平板和手机都一样。

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.2.5
