### ISSUE TITLE
界面点击交互的响应时间建议快一些

### ISSUE THREAD

**Issue by sunboy78** [yaoxieyoulei/mytv-android#179]
### 问题描述
目前2.2.4版本无论在使用触摸和遥控器时，点击激发事件总感觉有延迟，不跟手。

### 解决方案
提高事件的触发响应时间

### 其他
参照diyp、百川影音等类似app的事件响应时间

**Comment by kidneyisource** [comment]
你这都是小问题 播放ipv6画面卡顿才是大问题

**Comment by sunboy78** [comment]
楼上说的IPV6画面卡顿在我骁龙835平板和N1盒子上不是很明显。卡顿可能是 直播源质量不稳定 或 是现有单一解码方式的兼容性不佳导致。

解决方案建议：
提供多种解码方式（系统原生+IJK+EXO）让用户冗余选择，提高其兼容性。

**Comment by kidneyisource** [comment]
> 楼上说的IPV6画面卡顿在我骁龙835平板和N1盒子上不是很明显。卡顿可能是 直播源质量不稳定 或 是现有单一解码方式的兼容性不佳导致。
> 
> 解决方案建议： 提供多种解码方式（系统原生+IJK+EXO）让用户冗余选择，提高其兼容性。

不确定是不是解码的问题 因为上面也有人发现了这个现象 而且在2.2.0版本上又没有这个问题 其他版本都有问题 我刚刚也重新测试了一下确实是这样

**Comment by FRANKASEE** [comment]
> 楼上说的IPV6画面卡顿在我骁龙835平板和N1盒子上不是很明显。卡顿可能是 直播源质量不稳定 或 是现有单一解码方式的兼容性不佳导致。
> 
> 解决方案建议： 提供多种解码方式（系统原生+IJK+EXO）让用户冗余选择，提高其兼容性。

还不明显~~~~
有一点都不行！！解决方案是不会有的，我之前就提过，是代码平台的问题。

现在的办法是用2.2.0版本。所以版本只有这个可以正常使用！！！！！

要不去用1.4.4版本。。

翻翻我以前发的问题，已经被关闭:

   https://github.com/yaoxieyoulei/mytv-android/issues/80

   https://github.com/yaoxieyoulei/mytv-android/issues/90

**Comment by kidneyisource** [comment]
> > 楼上说的IPV6画面卡顿在我骁龙835平板和N1盒子上不是很明显。卡顿可能是 直播源质量不稳定 或 是现有单一解码方式的兼容性不佳导致。
> > 解决方案建议： 提供多种解码方式（系统原生+IJK+EXO）让用户冗余选择，提高其兼容性。
> 
> 还不明显~~~~ 有一点都不行！！解决方案是不会有的，我之前就提过，是代码平台的问题。
> 
> 现在的办法是用2.2.0版本。所以版本只有这个可以正常使用！！！！！
> 
> 要不去用1.4.4版本。。
> 
> 翻翻我以前发的问题，已经被关闭:
> 
> #80
> 
> #90

要不是你说用2.2.0我都准备放弃这个apk了
