### ISSUE TITLE
能不能考虑一下安卓4.4的电视，这批老电视也想用啊

### ISSUE THREAD

**Issue by gangzi8721** [yaoxieyoulei/mytv-android#187]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by word2007** [comment]
顶上去，希望开发大神能看到

**Comment by yaoxieyoulei** [comment]
技术问题无法实现

**Comment by tangqiu0205** [comment]
几十块钱买个电视盒子多香啊

**Comment by word2007** [comment]
> 技术问题无法实现  -----------请大佬想想办法吧。能支持安卓4，善莫大焉。

**Comment by chengnan049** [comment]
真没必要了，几十块买个新盒子
