### ISSUE TITLE
想建立一个群 大家可以一起交流使用过程中的问题 然后分享直播源 我只负责开贴 谁有建好的群麻烦回复在下面

### ISSUE THREAD

**Issue by kidneyisource** [yaoxieyoulei/mytv-android#188]
最好是微信群哈 
还有我今天发现ipv6的直播变得特别卡 测试发现不是app的问题 有可能是我网络的问题 不太确定 你们有这种情况吗

**Comment by kidneyisource** [comment]
我终于发现问题的原因了 大家一定要定时更新直播源 因为地址是一直在变的

**Comment by myworksfun** [comment]
Perhaps there is already a QQ group like this.😂

**Comment by kidneyisource** [comment]
> Perhaps there is already a QQ group like this.😂

where is the qq   tell me

**Comment by lishengwei** [comment]
![image](https://github.com/user-attachments/assets/4a172983-9618-4d3a-925a-a74f6a211696)

**Comment by danielliulihua** [comment]
怎么更新直播源？
