### ISSUE TITLE
添加ijkplayer支持

### ISSUE THREAD

**Issue by slipdaly** [yaoxieyoulei/mytv-android#189]
### 功能描述
添加ijkplayer支持

### 目标
exoplayer不支持组播，如果能添加ijkplayer支持就好了

### 解决方案
添加ijkplayer支持

### 其他
DIYP影音，tvBox

**Comment by slipdaly** [comment]
看了下代码支持ijk要改好多，要写一整套ijk相关的解码逻辑，估计不会支持了。
media3没提供ijk相关的库

**Comment by cani1see** [comment]
> 看了下代码支持ijk要改好多，要写一整套ijk相关的解码逻辑，估计不会支持了。 media3没提供ijk相关的库

我发现 allinone 前几个测试台都是 ERROR_CODE_DECODER_INIT_FAILED 我把ts下下来，用vlc放完全正常。不知道是不是这个问题。
奇怪的是我网上下的265的这台平板放不动，allinone提供的hevc却很正常
