### ISSUE TITLE
建议增加对网页直播的支持，可解决大部分节目源稳定性问题。

### ISSUE THREAD

**Issue by miaomiaosoft** [yaoxieyoulei/mytv-android#191]
### 功能描述
目前看电视最核心也是最头疼的问题倒不是播放器而是节目源，
要么自己找源要么等别人更新，到处去抓电视盒子的源，极不稳定，
但如果通过直接浏览网页并自动以全屏状态播放页面中的直播视频，
那么有相当多的中央台、卫视台和省市台、甚至台湾台（四季线上）都有官方提供的超级稳定的直播页面，
对这些节目来说可以长期甚至永久稳定收看。
举例：
央视全台：https://tv.cctv.com/live/
央视+卫视：https://www.yangshipin.cn/tv/home

### 解决方案
可参考相关项目：
https://github.com/hxh19950701/WebViewTvLive
https://github.com/Eanya-Tonic/CCTV_Viewer

**Comment by shichaoufo** [comment]
网页的打开太慢了，体验不咋样。况且楼主提到的那些参考项目已经很成熟了，直接用他们的app就行了，好像他们的也支持m3u8

**Comment by miaomiaosoft** [comment]
@shichaoufo 大多都是国内网站怎么可能慢，速度肯定要比直连M3U8久一点，但也在可接受范围，而且也可以屏蔽加载图片之类的无关元素进一步加速。
提到的两个项目，一个试了不能用，一个作者可能不太想继续更新，功能不全，有些M3U8或格式也是放不了。
