### ISSUE TITLE
网络连接异常或不支持IPv6，请检查网络设置

### ISSUE THREAD

**Issue by warthur1214** [yaoxieyoulei/mytv-android#194]
如题：
网络连接异常或不支持IPv6，请检查网络设置
ERROR_CODE_IO_NETWORK_CONNECTION_FAILED(2001)错误

版本：2.2.5
硬件：红米电视

**Comment by word2007** [comment]
同样的问题，似乎是直播源地址被屏蔽。。。ip6地址也无法播放。这么好的app，还能支持安卓4，如无法使用，简直太遗憾啦！

**Comment by warthur1214** [comment]
> 同样的问题，似乎是直播源地址被屏蔽。。。ip6地址也无法播放。这么好的app，还能支持安卓4，如无法使用，简直太遗憾啦！

是呀，我用ipv4到是可以播放。估计是联通宽带的问题，问客服说是 只有企业网络可以开ipv6。个人宽带是开不了啦

**Comment by warthur1214** [comment]
我打算换个直播源试试了

**Comment by lishengwei** [comment]
> 我打算换个直播源试试了



> > 同样的问题，似乎是直播源地址被屏蔽。。。ip6地址也无法播放。这么好的app，还能支持安卓4，如无法使用，简直太遗憾啦！
> 
> 是呀，我用ipv4到是可以播放。估计是联通宽带的问题，问客服说是 只有企业网络可以开ipv6。个人宽带是开不了啦

那是客服不懂忽悠你呢。现在国内是力推ipv6呢，你直接跟客服说我要ipv6上网，不支持就投诉。或者你知道你们小区装维电话，打电话说点好话跟装维师傅让他帮忙给你弄。

**Comment by word2007** [comment]
ip6测试是完全没问题的，应该是直播源的问题，感觉是ip6的直播源没有被解析。我更换了直播源，是可以播放的，但是似乎清晰度不高。也就是ip6的直播源完全没有被解析。

Shengwei Li ***@***.***> 于2024年11月8日周五 16:47写道：
