### ISSUE TITLE
4K频道画面偶尔抖动、局部花屏

### ISSUE THREAD

**Issue by ssyangchn** [yaoxieyoulei/mytv-android#196]
### 问题描述
我是用udpxy组播转的单播源，播放1080P的频道没问题，就是播放4K的频道每隔几秒画面会抖动一下，还有一点花屏。我用手机和电脑的potplayer看同样的频道没问题，所以应该可以排除是直播源的问题

### 复现步骤
使用本客户端观看udpxy组播转单播的源，播放cctv4k频道

### 预期行为
能正常播放

### 系统信息
电视是索尼x90l，32位安卓TV。软路由为下x86 n100 openwrt

### 相关截图或日志
![屏幕截图 2024-11-07 163534](https://github.com/user-attachments/assets/b1715c74-b9c4-4047-8cf6-cc0be48fc4a7)

**Comment by yaoxieyoulei** [comment]
尝试https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.2.7

**Comment by ssyangchn** [comment]
> 尝试https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.2.7

修复了
