### ISSUE TITLE
win11自带安卓模拟器，电脑支持ip6，但是总报2001代码错。安卓平板就没事。。。。

### ISSUE THREAD

**Issue by word2007** [yaoxieyoulei/mytv-android#200]
win11自带安卓模拟器，电脑支持ip6，1.44及以上版本（低版本未试）报2001代码错（网络连接异常或不支持ip6）。但同一网络下安卓平板就能正常播放。另外电脑是支持ip6的，太奇怪啦。

**Comment by Alonewader** [comment]
貌似WINDOWS的安卓模拟器不支持IPv6，更新版本或可解决。

**Comment by peter-pan** [comment]
我的电视也有这个错误，放了一会就报这个错误了
