### ISSUE TITLE
有画面，但没有声音。

### ISSUE THREAD

**Issue by Pixroc** [yaoxieyoulei/mytv-android#211]
联通的IPTV，一些台没有声音，画面正常，目前测试到的CCTV1, CCTV3, CCTV5都没有声音，可能跟解码有关。

**Comment by beijiahiddink** [comment]
实测使用IJKPlayer解码，使用fanmingming直播源大部分频道都有画面，没有声音，只有像CCTV6、CCTV8个别的几个频道有声音，这个问题比较影响使用体验，希望开发者能早点修复下
