### ISSUE TITLE
自己写的epg.xml文件好像无法解析

### ISSUE THREAD

**Issue by badgv** [yaoxieyoulei/mytv-android#219]
同一个xml文件，用手机的IPTV pro这个软件，能正确解析并显示节目预告，浏览器也能正常解析，上传文件必须.txt后续，希望修复下epg解析问题
[myepg.xml.txt](https://github.com/user-attachments/files/17961163/myepg.xml.txt)

**Comment by yaoxieyoulei** [comment]
需要.xml或.xml.gz结尾

**Comment by badgv** [comment]
> 需要.xml或.xml.gz结尾

我使用的时候是直接用.xml结尾的后缀，GITHUB不允许上传xml后缀的文件，所以我加了个.txt后缀上传上来以方便测试
