### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by maciakng** [yaoxieyoulei/mytv-android#22]
### 问题描述
设置里面的二维码及ip:端口的形式都无法打开配置页面，手机上提示打开失败

### 复现步骤
手机扫码或者浏览器输入电视ip

### 预期行为
希望修复手机扫码配置功能

### 系统信息
小米电视，安卓4.2

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by silverzhaojr** [comment]
问题可以重现，似乎是因为这里的 `baseUrl` 不对，好像不应该是 `127.0.0.1` 吧：

https://github.com/yaoxieyoulei/mytv-android/blob/main/app/src/main/res/raw/index.html#L129
```
129 const baseUrl = "http://127.0.0.1:10481"
```

**Comment by yaoxieyoulei** [comment]
已修复 [v1.4.1](https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.1)

**Comment by silverzhaojr** [comment]
版本 1.4.1 可以通过网页正常打开设置界面了，但是其中好像少了很多，没有了“多直播源”的设置项。

**Comment by yaoxieyoulei** [comment]
> 版本 1.4.1 可以通过网页正常打开设置界面了，但是其中好像少了很多，没有了“多直播源”的设置项。

目前网页的话就放一些电视端无法完成的操作，其他操作都在电视端设置中
