### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by dddd64693** [yaoxieyoulei/mytv-android#226]
### 问题描述
请提供一个清晰而简明的问题描述。
播放时提示视频解码器初始化失败，使用ijk内核播放时，有图像没有声音，设备是用移动魔百盒刷的安卓原生系统
### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
![image](https://github.com/user-attachments/assets/614da260-c40d-4c93-9703-fbcba37a4151)
![image](https://github.com/user-attachments/assets/aecee301-b3fe-42d3-beed-c83ab9285fb1)
![image](https://github.com/user-attachments/assets/00e1b954-ac11-4181-a141-22e9c3032f2f)

**Comment by newer15** [comment]
use 336

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.2.7
