### ISSUE TITLE
今天播放不了了。

### ISSUE THREAD

**Issue by lc122125237** [yaoxieyoulei/mytv-android#23]
播放源是不是挂了？左下角提示远程更新播放源失败，（是要搭梯子更新吗?）求作者更新。翘首以盼！！

**Comment by yaoxieyoulei** [comment]
默认源我这边没问题，你试一下手机上能不能打开这个链接：https://mirror.ghproxy.com/https://raw.githubusercontent.com/zhumeng11/IPTV/main/IPTV.m3u
