### ISSUE TITLE
你们有播放卡死的问题吗？

### ISSUE THREAD

**Issue by zg4321** [yaoxieyoulei/mytv-android#232]
最新版本，遇到有些源质量不好，放一会卡了后就卡死不动了，超时后也不会自动切换其它源，只有那种一开始就播不出来的源，自动超时后会切换源。
同一个播放列表同一个源，在其它的播放器里卡死后是可以超时自动切换源。
使用的手机，不知道你们有这个问题没。

**Comment by zg4321** [comment]
这个播放器做的特别好，看直播该有的功能都有，还比其他的播放器占用内存小，感谢大佬不断地维护和更新。

**Comment by zg4321** [comment]
> 最新版本，遇到有些源质量不好，放一会卡了后就卡死不动了，超时后也不会自动切换其它源，只有那种一开始就播不出来的源，自动超时后会切换源。
> 同一个播放列表同一个源，在其它的播放器里卡死后是可以超时自动切换源。
> 使用的手机，不知道你们有这个问题没。

补充一下，卡死后不会自动切换源，手动切换源没问题。

**Comment by zg4321** [comment]
发现了，是UDP和RTP类的地址，播放一两秒左右就会卡死，但是不会自动切换源

**Comment by Dev1l1323** [comment]
UDP和RTP类的地址是组播地址,,没转单播?

**Comment by zg4321** [comment]
> UDP和RTP类的地址是组播地址,,没转单播?

http://120.6.209.42:8866/udp/239.253.92.13:8008，http://123.113.237.160:8888/udp/239.3.1.124:8128这种的地址

**Comment by zg4321** [comment]
> UDP和RTP类的地址是组播地址,,没转单播?

http://60.164.128.167:8029/rtp/239.255.29.28:8231，http://120.6.209.42:8866/udp/239.253.92.13:8008这种类型的地址
