### ISSUE TITLE
【功能请求】关于经典选台界面的 EPG 节目单显示方式

### ISSUE THREAD

**Issue by silverzhaojr** [yaoxieyoulei/mytv-android#24]
### 功能描述
目前 mytv 支持了经典的三段式选台界面，这个实在太好了！之前一直习惯了 DIYP 的显示模式，现在 mytv 新增了这个界面后，用起来顺手多了。

建议反馈：
当前点击到频道列表中的某个频道时，在右边会自动展开 EPG 节目单，有时候在快速切换频道时，会显得有些眼花缭乱。可否和 DIYP 一样，焦点在频道列表时，按一次右方向键才展开 EPG 节目单，按左方向键收起节目单。如果节目单已经被展开，那么在切换频道时，节目单依然处于展开状态。

**Comment by yaoxieyoulei** [comment]
已优化 [v1.4.1](https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.1)

**Comment by silverzhaojr** [comment]
谢谢！

刚刚试了下 1.4.1 版本，有个建议：

目前在右方向键展开节目单后，若是按左方向键，会关闭节目单，且同时焦点会直接切到频道列表上，感觉有些不太方便。建议这时候只是关闭节目单，焦点依然停留在当前频道上。

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.2
