### ISSUE TITLE
【功能建议】关于收藏列表和时间的显示方式

### ISSUE THREAD

**Issue by silverzhaojr** [yaoxieyoulei/mytv-android#25]
### 功能描述

1. 关于收藏列表打开方式
在经典三段界面模式下，收藏列表和全部列表的切换是通过在频道分类上按左方向键来实现，看起来感觉有些不太直观。建议是否可以像 DIYP 一样，将“我的收藏”直接和“频道分类”并列，放在顶端最上方呢？这样整个列表展开界面也和全部列表一致。当然这个只是我的一家之言，作者当前的实现方式可能有自己的考虑。

2. 关于“收藏启用”设置项
设置中有一项“收藏启用”，之前我理解成禁用之后，收藏列表就完全打不开，后来发现并非如此，其实是指“长按收藏”这个动作被禁止。是否改成“启用长按收藏”可以更明确些？

3. 关于时间显示设置
目前关于时间显示的设置，只有“隐藏”和“常显”选项，建议是否可以改成按 OK 键在显示频道列表时右上角同步显示时间，或者按菜单键出现频道设置时同步显示时间？

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.2
