### ISSUE TITLE
希望加入台标显示的功能

### ISSUE THREAD

**Issue by xiaomageaaa** [yaoxieyoulei/mytv-android#28]
希望加入台标显示的功能，通过M3U或者像epg那样，配置一个url可以实现显示台标

**Comment by ssiop789** [comment]
其实那个网格模式不错。选频道时候频道铺全屏，简单明了，还可以完全展示台标。

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.0.0
