### ISSUE TITLE
【功能建议】关于切换频道分类时的焦点问题

### ISSUE THREAD

**Issue by silverzhaojr** [yaoxieyoulei/mytv-android#31]
### 重现步骤
假设有两个频道分类“央视”和“卫视”，先切换节目到 CCTV-2，然后按左方向键回到频道分类列表，按下方向键到“卫视”分类上，再按上方向键回到“央视”分类，会发现焦点立刻自动跳到了右侧的 CCTV-2 上，而不是停留在“央视”上。这样显得比较突兀且不太自然。

### 建议
可否在切换到“央视”分类时，保持焦点在频道分类列表上，在按右方向键时再跳到 CCTV-2 上。

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.2
