### ISSUE TITLE
【功能建议】关于断线自动重连，或者超时换源

### ISSUE THREAD

**Issue by huofengkuangwu** [yaoxieyoulei/mytv-android#32]
看着某个频道呢，时间长了也可能是网络原因，就卡那显示个不能播放的几个英文字母不动了，必须要手动换台到别的频道，然后再切回来才能继续看，这个是不是可以增加这个自动重连这个功能。

另外个人感觉作为一个电视播放器没有必要每次打开都检测更新，每次都会有个提示，这个不太喜欢。检不检测更新决定权交给用户感觉比较好。

**Comment by yaoxieyoulei** [comment]
试试 https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.3
