### ISSUE TITLE
声音太小了，比其他app声音小

### ISSUE THREAD

**Issue by kilvn** [yaoxieyoulei/mytv-android#33]
匪讯T1 yyform装了西瓜视频，爱优腾，kodi等，就刚装的mytv-android声音太小，机顶盒音量要调高其他app音量的2倍，希望看下是什么原因。

还有在t1上的开机自启无效、在线更新无效，永远都是显示最新版本，即使有了更新的release

**Comment by yaoxieyoulei** [comment]
1、声音的话应该跟直播源有关，你试着换个直播源试试
2、开机自启应该是设备不支持，
3、在线更新正常的，最新版本就是1.4.1，1.4.2预发行不算

**Comment by kilvn** [comment]
我从中央1到中央13都试了，感觉是app偏小，之前装mytv这块没问题

**Comment by whybm** [comment]
> 我从中央1到中央13都试了，感觉是app偏小，之前装mytv这块没问题

这个用的是fanmingming的源，本身就是声音小，可以自己换源。my-tv用的是央视频，不一样
