### ISSUE TITLE
进入设置界面，按返回键不能返回播放界面

### ISSUE THREAD

**Issue by AppleMate60pro** [yaoxieyoulei/mytv-android#34]
### 问题描述

进入设置后，按返回键不会返回播放界面

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
请描述你期望的正确行为或结果。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by yaoxieyoulei** [comment]
尝试解决 https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.2
