### ISSUE TITLE
对画面模式的比例能否做成全局的而不是针对每个频道

### ISSUE THREAD

**Issue by shaping520** [yaoxieyoulei/mytv-android#37]
### 功能描述
对画面模式的比例能否做成全局的而不是针对每个频道

### 目标
对画面模式设置为16：9后能够对全部频道都起作用，而不是只针对这个直播源；现在的现象是会自动根据视频的分辨率进行画面设置，我想固定为全屏或16：9

### 解决方案
做成全局设置，每次播放前都先读取下这个配置进行画面的设置

### 其他
DIPY中是全局的

**Comment by iseku** [comment]
附议

**Comment by zshao333** [comment]
附议，这个提议好，目前的是针对每个台的，而且不会记忆。希望大佬能加上全局比例调节

**Comment by yaoxieyoulei** [comment]
试试 https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.3
