### ISSUE TITLE
希望能支持多直播源，以及在首页便捷的切换直播源

### ISSUE THREAD

**Issue by ybjbox** [yaoxieyoulei/mytv-android#38]
本地区的宽带给了公网V4就不给V6，无法使用默认源。希望能添加添加多个直播源，这样就能同时使用自己的V4直播源和tvbox。最好在首页能便捷的切换直播源就更完美了✌️︎

顺便夸一下，作者是有审美的，图标和界面都比隔壁那个好太多了！！

**Comment by yaoxieyoulei** [comment]
可以添加自己的直播源
访问以下网址：http://<设备IP>:10481
