### ISSUE TITLE
遥控器回到主页后小窗口播放

### ISSUE THREAD

**Issue by Soooape** [yaoxieyoulei/mytv-android#39]
### 问题描述
按了遥控器主页按钮后，应用没有退出而是自动右下角小窗口悬浮播放，无法返回全屏或者退出

### 复现步骤
切换其他app/切换信号源/投屏均无法退出应用

### 预期行为
在设置中添加关闭小窗播放的选项

### 系统信息
设备：雷鸟75S535D Pro
系统：V8-T652T03-LF1V145

**Comment by yaoxieyoulei** [comment]
双击返回退出应用

**Comment by yaoxieyoulei** [comment]
按主页按钮进入画中画模式，在悬浮窗模式下试一下双击主页键应该能设置这功能

**Comment by gavinmeng822** [comment]
话说CCTV5 IPV4怎么看？感谢大佬

**Comment by Soooape** [comment]
> 按主页按钮进入画中画模式，在悬浮窗模式下试一下双击主页键应该能设置这功能

![image](https://github.com/user-attachments/assets/92253d3a-ff8b-4d69-861e-75f9dfa59dc7)

![image](https://github.com/user-attachments/assets/036020ab-8c39-4b71-bedd-f3d4fa58ef3a)

双击返回键、主页键均无反应，长按主页键出来的是应用历史，看来雷鸟不支持这个设置

**Comment by conancheng** [comment]
> 按主页按钮进入画中画模式，在悬浮窗模式下试一下双击主页键应该能设置这功能

小米电视双机是调出任务后台，所以这个操作无效

**Comment by yaoxieyoulei** [comment]
试试 https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.3

**Comment by Soooape** [comment]
> 试试 https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.3

可以了，感谢🙏
