### ISSUE TITLE
最新版1.4.2画中画窗口后没法恢复正常窗口

### ISSUE THREAD

**Issue by mylube** [yaoxieyoulei/mytv-android#40]
### 问题描述
我的电视机是海信电视，安卓9的，当运行mytv按下主页键后（不特意按这主页键有时候也会没当心碰到，特别是老人操作更会），出现画中画窗口并播放节目，但是不管是按遥控器的返回键，还是按您说的主页键连续两次，都没法恢复电视的正常播放，也没法退出画中画或此app，然后我再选其他app可以播放，但这画中画就会中断播放并出错（显示播放失败画面），此时只能把电视关机再重新开机。

### 复现步骤
请提供复现该问题所需的具体步骤。

### 预期行为
能在设置里面自主选择开启/关闭画中画功能，或者修复遥控按返回时能恢复正常窗口播放

### 系统信息
海信电视65E7G，VIDAA ，安卓9.0

**Comment by mylube** [comment]
双击主页键、或者双击返回键都没法退出或恢复正常

**Comment by yaoxieyoulei** [comment]
可以问一下客服怎么操作，下个版本优化

**Comment by gybin02** [comment]
确实是 这样。画中画挺奇怪的

**Comment by yaoxieyoulei** [comment]
试试 https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.3
