### ISSUE TITLE
弱问一句 软路由openwrt如何打开ipv6

### ISSUE THREAD

**Issue by derekling** [yaoxieyoulei/mytv-android#41]
求助。怎么弄也不行，一级路由有IPv6

**Comment by deskOfDafa** [comment]
电信都是假ipv 6，服了

**Comment by hank8884** [comment]
> 求助。怎么弄也不行，一级路由有IPv6

要打开ipv6解析，可以去油管搜一下，另外如果主路由是软路由，软路由的lan口要接硬路由的wan口
