### ISSUE TITLE
真心希望支持安卓4.x

### ISSUE THREAD

**Issue by smgfw** [yaoxieyoulei/mytv-android#42]
### 功能描述
如果长期维护的话，真心希望支持安卓4.x

**Comment by momada** [comment]
实在不行的话，支持安卓5也行

**Comment by iougemini** [comment]
+1，家里的老电视用不上啊

**Comment by yaoxieyoulei** [comment]
可以用这个：https://tansuo.lanzouo.com/ilBOj1kywj2j
https://www.iptvindex.com/kan-dian-shi

**Comment by iougemini** [comment]
> 可以用这个：https://tansuo.lanzouo.com/ilBOj1kywj2j https://www.iptvindex.com/kan-dian-shi

好的，谢谢啊

**Comment by vrichv** [comment]
android 4.4可以用我fork原作者的版本 https://github.com/vrichv/my-tv-0

**Comment by smgfw** [comment]
开心了一下 mytv0也支持4.x了，帅不过两秒，又不开心了4.4以上。。😄我的小米电视2是安卓4.3😳

**Comment by vrichv** [comment]
> 开心了一下 mytv0也支持4.x了，帅不过两秒，又不开心了4.4以上。。😄我的小米电视2是安卓4.3😳
> […](#)
> 在 2024年7月24日，22:34，R ***@***.***> 写道： ﻿ android 4.4可以用我fork原作者的版本 https://github.com/vrichv/my-tv-0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

代码理论上4.2以上完全没有问题，你只需要动动小手，修改个依赖和api版本就能编译出来了
只是这些老旧设备有很多诡异的问题，搞起来超级烦躁，没设备调试不想兼容

**Comment by smgfw** [comment]
> > 开心了一下 mytv0也支持4.x了，帅不过两秒，又不开心了4.4以上。。😄我的小米电视2是安卓4.3😳
> > […](#)
> > 在 2024年7月24日，22:34，R _**@**_.***> 写道： ﻿ android 4.4可以用我fork原作者的版本 https://github.com/vrichv/my-tv-0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.
> 
> 代码理论上4.2以上完全没有问题，你只需要动动小手，修改个依赖和api版本就能编译出来了 只是这些老旧设备有很多诡异的问题，搞起来超级烦躁，没设备调试不想兼容

😄，发财的小手搞不了这些啊，一点都不懂。谢谢了。

**Comment by smgfw** [comment]
> > 开心了一下 mytv0也支持4.x了，帅不过两秒，又不开心了4.4以上。。😄我的小米电视2是安卓4.3😳
> > […](#)
> > 在 2024年7月24日，22:34，R _**@**_.***> 写道： ﻿ android 4.4可以用我fork原作者的版本 https://github.com/vrichv/my-tv-0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.
> 
> 代码理论上4.2以上完全没有问题，你只需要动动小手，修改个依赖和api版本就能编译出来了 只是这些老旧设备有很多诡异的问题，搞起来超级烦躁，没设备调试不想兼容

我看你增加了ijk和jb版，那个jb写着4.1/4.2，是不是只适配4.1和4.2，不适配4.3？

**Comment by smgfw** [comment]
> android 4.4可以用我fork原作者的版本 https://github.com/vrichv/my-tv-0
