### ISSUE TITLE
希望增加IPV4源

### ISSUE THREAD

**Issue by lovekov** [yaoxieyoulei/mytv-android#43]
### 功能描述
请提供对所请求功能的清晰描述。
希望增加IPV4源，目前IPV6还没有完全普及
### 目标
请描述你希望通过这个功能实现的目标。
可以默认IPV4或者IPV6源，用户根据实际情况，切换源
### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。
提供IPV4、IPV6源，可以切换使用
### 其他
请提供已实现该功能或类似功能的应用

**Comment by yaoxieyoulei** [comment]
可以试一下这个：https://github.com/yuanzl77/IPTV

**Comment by lovekov** [comment]
> 可以试一下这个：https://github.com/yuanzl77/IPTV

谢谢
