### ISSUE TITLE
Cant send m3u file from local PC.

### ISSUE THREAD

**Issue by newer15** [yaoxieyoulei/mytv-android#44]
How to send m3u file from local PC, thanks.

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by yaoxieyoulei** [comment]
not support local file

**Comment by newer15** [comment]
Thanks for reply. 自定义直播源 function is useless.

**Comment by newer15** [comment]
感谢你的辛勤劳动。这个APP比别的直播好很多,花了好多心思。谢谢!

目前情况是我把直播源挂到网盘上解决了笫一个问题但笫二个问题来了。

直播源缓存时间只有0到24小时,能不能设成无限长这样就不怕网盘断网沒法看了?

再次感谢!

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.0.0
