### ISSUE TITLE
希望优化一下App的LOGO

### ISSUE THREAD

**Issue by hank8884** [yaoxieyoulei/mytv-android#45]
### 功能描述
Logo不能自适应电视图标的尺寸

### 目标
如何可以参照一下小米电视的图标logo，谢谢

**Comment by hank8884** [comment]
![1721312718106_edit_27078816679721](https://github.com/user-attachments/assets/d3d37bb2-ff53-4595-ad9b-21cbda3bce36)
这个大小应该可以适应大图标

**Comment by kilvn** [comment]
> ![1721312718106_edit_27078816679721](https://private-user-images.githubusercontent.com/121142736/350005540-d3d37bb2-ff53-4595-ad9b-21cbda3bce36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODcyNTksIm5iZiI6MTcyMTk4Njk1OSwicGF0aCI6Ii8xMjExNDI3MzYvMzUwMDA1NTQwLWQzZDM3YmIyLWZmNTMtNDU5NS1hZDliLTIxY2JkYTNiY2UzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwOTQyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODViMWMwZmY3ZTRkYTJlZmM4YjE5YWM0ZDk5OGQ0NTRhNGVhMzU3MWFlZDA2YzVhNjUwMGY4NzdkNTdmNDE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.umua_Cyjwbur1OGoaUvR9Wo88dlXLmON6LV2feaZdAo) 这个大小应该可以适应大图标

双手赞成

**Comment by qiang1352** [comment]
我自己下载源码，修改一下logo图标。重新打包的，适配了电视机

**Comment by Emtier** [comment]
这样好看不![image](https://github.com/user-attachments/assets/e7089b96-495b-4b34-b47b-feefda2429b2)

**Comment by lishengwei** [comment]
赞成更换图标。其实我更贪心，建议换掉“我的电视”这个名字 🐶。

**Comment by beijiahiddink** [comment]
现在的这个Logo就不能换个吗，也太丑了
