### ISSUE TITLE
安卓4.4电视盒子，安装mytv-android-V1.4.2，闪退

### ISSUE THREAD

**Issue by hegan001** [yaoxieyoulei/mytv-android#47]
### 问题描述
安卓4.4电视盒子，安装mytv-android-V1.4.2，闪退

### 复现步骤
闪退

### 预期行为
建议修复

### 系统信息
安卓4.4电视盒子
### 相关截图或日志
闪退

**Comment by yaoxieyoulei** [comment]
只支持Android5及以上

**Comment by hegan001** [comment]
好的，收到。
