### ISSUE TITLE
【功能请求】支持查看 EPG 节目单的功能

### ISSUE THREAD

**Issue by silverzhaojr** [yaoxieyoulei/mytv-android#5]
### 功能描述
目前每个频道只能查看当前播放节目和下一个要播放的节目，没有办法查看之前更多时间的节目或者后面的节目。请求增加该功能。

### 其他
DIYP 支持该功能，在当光标移到每个频道上时，直接按方向右键即可展开当前频道的 EPG 节目单。

**Comment by yaoxieyoulei** [comment]
v1.3.0已支持，目前仅展示了当天节目单

**Comment by silverzhaojr** [comment]
非常感谢！

1. 现在在频道名称上按菜单键打开节目单时，出现的动画感觉有些突兀，有点像从天而降的样子。不知道是否可以进一步优化，不过这个不急；
2. 在节目单打开时，可否支持左右键直接切换相邻频道的节目单，这样方便预览每个频道的节目。DIYP 在节目单展开时，方向键上下遍历频道时，节目单会随之变化；
3. 不知道以后是否会支持节目回放呢？

**Comment by yaoxieyoulei** [comment]
动画是因为掉帧了。节目回放有点麻烦，涉及的东西比较多
