### ISSUE TITLE
在推送自定义源以后，重启应用就再也打不开了

### ISSUE THREAD

**Issue by haodadajipai** [yaoxieyoulei/mytv-android#51]
### 问题描述

不配置自定义源没问题。在推送自定义源以后，重启应用就再也打不开了，只能卸载重装。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。
雷鸟电视，安卓11

**Comment by haodadajipai** [comment]
> 是一直加载中，还是闪退？加载中可以按设置键打开设置界面

闪退，啥都没出现

**Comment by yaoxieyoulei** [comment]
直播源能否发一下

**Comment by haodadajipai** [comment]
> 直播源能否发一下

你提醒我以后，我用IPTV Checker重新读取了一下再导出m3u8源，就可以了。但是之前的用IPTV PRO之类的都是没问题的。包括IPTV Checker读取也是没问题。

感谢
