### ISSUE TITLE
直播源缓存时间

### ISSUE THREAD

**Issue by newer15** [yaoxieyoulei/mytv-android#52]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by newer15** [comment]
直播源缓存时间只有0到24小时,能不能设成无限长或手动更新这样就不怕网盘断网沒法看了?

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.0.0
