### ISSUE TITLE
建议优化收藏中切换频道的逻辑、并可调整已收藏频道的顺序

### ISSUE THREAD

**Issue by jdb110** [yaoxieyoulei/mytv-android#54]
### 功能描述
逐级切换：假设在频道收藏中收藏了央视6、央视9这2个频道，如果现在在收藏中选中了央视6，那么上下键切换频道的时候下一个频道应该是央视9。从央视9切换下一个频道的时候，因为收藏中频道已经到了最后一个，跳到一级菜单中的央视节目中，选中第一个频道，即央视1.

收藏频道顺序的调整：可以在高级设置中对收藏频道顺序进行调整。

### 目标
收藏节目的切换是最多的，常看的频道就几个。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.0.0
