### ISSUE TITLE
直播源更新时间设置问题反馈

### ISSUE THREAD

**Issue by FRANKASEE** [yaoxieyoulei/mytv-android#58]
### 问题描述
直播源更新时间设置无法设置24小时或更多时间

### 复现步骤
首次打开软件默认为24小时更新，一旦更改后只能设置为23小时

### 预期行为
希望能调整为24小时/两天/三天/一周

### 系统信息
安卓9.0盒子

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by yaoxieyoulei** [comment]
频道管理
