### ISSUE TITLE
【问题反馈】斗鱼直播源链接无法播放

### ISSUE THREAD

**Issue by silverzhaojr** [yaoxieyoulei/mytv-android#6]
### 问题描述
似乎斗鱼的直播源链接都无法播放。

### 复现步骤
在直播源文件中增加一个斗鱼直播源，如：

> 陈翔六点半,http://epg.112114.xyz/douyu/2132902

### 预期行为
可以正常播放。

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

Redmi TV XPro75, Android 9。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。
![scrot](https://github.com/yaoxieyoulei/mytv-android/assets/4557341/d7c6bd0f-7669-4e5a-94c5-b0187724c4f3)

**Comment by yaoxieyoulei** [comment]
因为链接没有类似.m3u8之类后缀，导致没识别出格式
