### ISSUE TITLE
希望增加回放功能与频道列表管理功能

### ISSUE THREAD

**Issue by FRANKASEE** [yaoxieyoulei/mytv-android#60]
### 功能描述
增加派大星的直播源历史回放功能，增加DIYP的频道管理功能

### 目标
可以回放电视节目，管理网络订阅源不需要的频道。

### 解决方案
参考派大星与DIYP的开源代码。

### 其他
派大星、DIYP

**Comment by yaoxieyoulei** [comment]
频道管理 https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.0.0
