### ISSUE TITLE
希望能优化一下低分辨率设备的菜单布局

### ISSUE THREAD

**Issue by gujiangjiang** [yaoxieyoulei/mytv-android#61]
一些DLP的投影仪还在使用480x800分辨率，使用这个应用没什么问题，但是会有两个地方最好能优化一下：
1、应用图标模糊，应该是原生没有低分辨率图标导致的
2、设置页面字体太小，虽然应用内有调节字体缩放的选项，但是那个仅针对播放页，设置菜单无效，设置的时候基本看不清字，希望能够针对低分辨率设备优化，最好能自动根据不同的分辨率应用不同的整体缩放比例，可能会更好。

谢谢。

![SAVE_20240727_014543](https://github.com/user-attachments/assets/1039abe9-08c3-44fd-b0de-cf7124c9eb68)
![SAVE_20240727_014723](https://github.com/user-attachments/assets/847b5aeb-016b-4581-87c7-b47b2be3c4bd)
![SAVE_20240727_014739](https://github.com/user-attachments/assets/f6bd1b14-0702-42d6-a328-72047ab147eb)

**Comment by yaoxieyoulei** [comment]
试试https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.0.0

**Comment by gujiangjiang** [comment]
@yaoxieyoulei 
非常感谢您，界面的问题解决了，如图所示，已经完美自动适配了低分辨率设备
![SAVE_20240801_190542](https://github.com/user-attachments/assets/ba4c9ee9-e993-4590-af79-c187c861928f)

![SAVE_20240801_190559](https://github.com/user-attachments/assets/2ee743f8-3a5d-4930-aba2-1d5f8bf17f4c)

但是软件的图标依然有问题，不知道什么情况。。。还是模糊的状态，同样的情况还出现在kodi，其他软件目前看来没问题，您有空的话再帮忙排查一下，感谢感谢
![Screenshot_2024-08-01-19-03-18-099_com didjdk adbhelper](https://github.com/user-attachments/assets/52766238-4644-422c-a998-fedefcf62d40)
![SAVE_20240801_190459](https://github.com/user-attachments/assets/62360d65-3f3d-4dc2-87c0-414317118043)
