### ISSUE TITLE
可以增加一个隐藏group的功能

### ISSUE THREAD

**Issue by bovindev** [yaoxieyoulei/mytv-android#62]
### 功能描述
请提供对所请求功能的清晰描述。
现在有个显示精简列表的功能，只有显示央视和卫视。可否增加一个自定义显示的功能，比如说只显示那几个分组或是隐藏那几个分组。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.0.0
