### ISSUE TITLE
海信电视 安装1.4.2版本播放不了

### ISSUE THREAD

**Issue by linhertz** [yaoxieyoulei/mytv-android#63]
### 问题描述
安装后播放不了。播放失败， IO_NETWORK_CONNECTION_FAILED(2001)

### 系统信息
Andirod 6.0以上。

**Comment by yaoxieyoulei** [comment]
可能网络不支持ipv6

**Comment by linhertz** [comment]
奥，是的，把IPV6功能打开就可以看了！
