### ISSUE TITLE
有没有快捷方式添加一个本地电视台的直播地址，或者修改现有默认源替换一条记录？

### ISSUE THREAD

**Issue by jackliu163** [yaoxieyoulei/mytv-android#65]
### 功能描述
有没有快捷方式添加一个本地电视台的直播地址？或者修改现有默认源替换一条记录？

### 目标
添加或者变更一个本地电视台

### 解决方案
添加自定义源和节目清单太多了，我只想在默认中加一个

**Comment by yaoxieyoulei** [comment]
无法实现
