### ISSUE TITLE
电视播放画面比例问题

### ISSUE THREAD

**Issue by xiaolaofu0** [yaoxieyoulei/mytv-android#66]
### 问题描述
部分资源分辨率是 726×576 默认比例为 4:3 每次都要修改为 16:9，切换到下一个台再返回又变成 4:3 了

### 复现步骤
设置为直播源为精简，47台，甘肃卫视ipv6，

### 预期行为
希望能有一个全局设置.全局为4:3和全局16:9的模式
![Uploading image.jpg…]()

### 系统信息
请提供关于您的环境的详细信息，包括操作系统、浏览器版本等。

### 相关截图或日志
如果有的话，请提供相关的截图、错误日志或其他有助于解决问题的信息。

**Comment by xiaolaofu0** [comment]
![Uploading image.jpg…]()
[](url)

**Comment by yaoxieyoulei** [comment]
试试 https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.3

**Comment by xiaolaofu0** [comment]
全局比例问题解决，目前电视使用未发现异常
