### ISSUE TITLE
问题反馈:CCTV16 4K奥运台，只运行在1920*1080分辨率，无法以4k分辨率显示

### ISSUE THREAD

**Issue by beetabin** [yaoxieyoulei/mytv-android#69]
### 问题描述
问题反馈:CCTV16 4K奥运台，只运行在1920*1080分辨率，无法以4k分辨率显示

### 复现步骤
CCTV16 4K奥运台，只运行在1920*1080分辨率，无法以4k分辨率显示

### 预期行为
以4k模式显示

### 系统信息
索尼(SONY)KD-55X8588G
Android 10

### 相关截图或日志
见附件
![image](https://github.com/user-attachments/assets/5c02b913-25b5-4ab6-97f1-4fa0986ebbd0)

**Comment by yaoxieyoulei** [comment]
直播源问题
