### ISSUE TITLE
在系统设置中关闭画中画选项后出现bug

### ISSUE THREAD

**Issue by wjz2001** [yaoxieyoulei/mytv-android#71]
### 问题描述
关闭画中画后，如果按主页键回到主页然后再进入软件就会显示播放失败FAILED_RUNTIME_CHECK(1004)

### 复现步骤
在系统设置中关闭画中画权限
进入软件正常播放电视台
按主页键返回主页
再次进入软件，显示播放失败

### 预期行为
即便按主页键回到主页然后再进入软件也不会播放失败

### 系统信息
设备是hk1box，系统是安卓9

**Comment by yaoxieyoulei** [comment]
试试 https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.3

**Comment by wjz2001** [comment]
> 试试 https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.3

11已解决
