### ISSUE TITLE
没有本地编译环境，麻烦直接上架APK

### ISSUE THREAD

**Issue by zzzbaba** [yaoxieyoulei/mytv-android#75]
### 功能描述
请提供对所请求功能的清晰描述。

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by FRANKASEE** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.0.0

**Comment by zzzbaba** [comment]
非常感谢，APP很好用

FRANKASEE ***@***.***> 于2024年8月5日周一 16:48写道：
