### ISSUE TITLE
关于收藏频道无法缓存功能

### ISSUE THREAD

**Issue by FRANKASEE** [yaoxieyoulei/mytv-android#78]
### 功能描述
收藏的频道，在切换其他直播源后还可以继续在收藏列表内正常观看

### 目标
在不同的订阅内点击收藏后，将收藏的频道源单独缓存添加到一个文件内，该文件永久不被删除，跟随订阅同步更新，如果无法实现同步更新，可以先实现手动更新

### 解决方案
使用现有开源代码

### 其他
参考派大星的频道收藏功能

**Comment by yaoxieyoulei** [comment]
切换其他直播源后，因为频道名称变了所以看不到

**Comment by FRANKASEE** [comment]
派大星的做法是，频道被加入收藏时会缓存生成一个收藏的本地文件，同时，会提取这个频道的地址，然后添加写入到本地文件中，在切换不同远程订阅时，本地缓存的频道收藏文件并存，无论如何切换订阅，不影响已经收藏的缓存频道，同时软件保存调用本地缓存的频道，保持本地和远程订阅同时运行
