### ISSUE TITLE
关于EPG七天回放功能问题反馈

### ISSUE THREAD

**Issue by FRANKASEE** [yaoxieyoulei/mytv-android#79]
### 问题描述
使用EPG回放显示该功能未实现

### 复现步骤
播放源在派大星和tivimate都可以正常回放。
播放源：https://mirror.ghproxy.com/https://raw.githubusercontent.com/YanG-1989/m3u/main/Gather.m3u
EPG：APP自带第二个，回看七天
自定义EPG：https://live.fanmingming.com/e.xml

### 预期行为
正常回放

### 系统信息
安卓9.0电视盒子。

### 相关截图或日志

![Screenshot_20240805-164518](https://github.com/user-attachments/assets/cceb8464-e33e-4c1e-9ac5-2d97ef408908)

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.1.0
