### ISSUE TITLE
自动更新的优化建议

### ISSUE THREAD

**Issue by Exlany** [yaoxieyoulei/mytv-android#8]
### 功能描述
1.目前主要是给家里老人使用，在电视上的操作是选中应用更新，然后长按OK键才会触发更新，点按OK键只是跳出更新日志。希望在点按OK键时也能触发更新。
2.希望在APP有个开关设置，能够开启APP时获得自动更新的确认弹窗，方便简化更新操作（主要是目前步骤比较多，对老人不友好）

### 目标
主要是希望在体验上能简化、更傻瓜化，家里老人记忆不好，教很多次也记不住。

### 其他
类似[FongMi/TV](https://github.com/FongMi/TV)

**Comment by yaoxieyoulei** [comment]
功能已实现，但老人用的话没必要频繁更新，只要维护自定义直播源就行了
