### ISSUE TITLE
关于使用EXOpalyer播放画面卡顿问题反馈#bug

### ISSUE THREAD

**Issue by FRANKASEE** [yaoxieyoulei/mytv-android#80]
### 问题描述
使用安卓9.0电视盒子/三星note10手机，my-tv2.0版本播放出现画面卡顿

### 复现步骤
正常播放画面卡顿闪烁/三星手机有短暂卡顿，需要仔细观看

### 预期行为
希望同步my-tv1.4.3的内核，1.4.3没有这个问题。或出一个后台自定义UA推送播放器的教程

### 系统信息
移动高清电视盒子B860AV3.2-M,存储4+32，芯片S905L3(B)，安卓9.0/三星note10安卓12.0

### 相关截图或日志
画面卡顿视频地址：https://www.bilibili.com/video/BV1eiYKeEEbU/?spm_id_from=333.999.0.0

**Comment by FRANKASEE** [comment]
2.1版本依然没有解决

**Comment by yaoxieyoulei** [comment]
https://www.123pan.com/s/kuXhjv-jlVIA.html  提取码:8gFz
试下这个，降低了播放器版本
