### ISSUE TITLE
tv2.1.0打开黑屏，有声音

### ISSUE THREAD

**Issue by liqiangsky** [yaoxieyoulei/mytv-android#86]
### 问题描述
黑屏
### 复现步骤
打开就黑屏

### 预期行为
正常显示

### 系统信息
红米K20PRO Android11

### 相关截图或日志
![Screenshot_2024-08-10-22-21-44-471_top yogiczy mytv tv](https://github.com/user-attachments/assets/eead15bd-77af-45e5-9029-8ab973364c3b)

**Comment by lele1307** [comment]
遇到了相同问题

**Comment by liqiangsky** [comment]
> 遇到了相同问题

2.0.0正常

**Comment by qiang1352** [comment]
我也遇到了

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.1.0
