### ISSUE TITLE
2.1.0版本的画面黑屏，有声音。1.4.3版本只有ipv4的视频能看，ipv6的播放源全都黑屏没有声音。

### ISSUE THREAD

**Issue by 907597029** [yaoxieyoulei/mytv-android#88]
2.1.0版本的画面黑屏，有声音。1.4.3版本只有ipv4的视频能看，ipv6的播放源全都黑屏没有声音。

**Comment by 907597029** [comment]
ipv6 的播放源全都是 timeout（2002）报错，不知道为什么会这样。

**Comment by d1ngx** [comment]
+1

**Comment by d1ngx** [comment]
重启一下路由器就好了

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.1.0
