### ISSUE TITLE
使用ijkmediaplayer替代exoplayer

### ISSUE THREAD

**Issue by caixxxin** [yaoxieyoulei/mytv-android#9]
### 功能描述
使用ijkmediaplayer替代exoplayer做视频解码。

### 目标
解决旧设备使用exoplayer播放视频卡顿的问题。

### 解决方案
使用ijkmediaplayer做视频解码。

### 其他
tvbox可以选择解码器，使用ijk解码流畅，而exo画面会卡顿。
另外，大佬会考虑兼容安卓4.4的设备吗？

**Comment by yaoxieyoulei** [comment]
项目所使用jetpack compose不支持安卓4.4
