### ISSUE TITLE
v1.4.3版本设置页面进不去

### ISSUE THREAD

**Issue by LL3706** [yaoxieyoulei/mytv-android#92]
### 功能描述
输入ip和端口，设置页面进不去，显示白屏

### 目标
请描述你希望通过这个功能实现的目标。

### 解决方案
如果你有任何关于如何实现这个功能的想法或建议，请在这里提供。

### 其他
请提供已实现该功能或类似功能的应用

**Comment by yaoxieyoulei** [comment]
https://github.com/yaoxieyoulei/mytv-android/releases/tag/v1.4.4
