### ISSUE TITLE
最新版打开所有频道提示播放失败

### ISSUE THREAD

**Issue by sihai2933** [yaoxieyoulei/mytv-android#93]
![image](https://github.com/user-attachments/assets/5a5f13c3-bce2-4d0d-a009-bb85a18ce7c3)

**Comment by myworksfun** [comment]
![btv](https://github.com/user-attachments/assets/b076560f-37ec-4fe3-9ee7-c10449730f60)
_此处疑似可以正常播放，肯能是网络的问题，重启试试看，ipv6是必须要有的_😄 @sihai2933
