### ISSUE TITLE
问题反馈: 添加自定义直播源app崩溃（闪退）

### ISSUE THREAD

**Issue by myworksfun** [yaoxieyoulei/mytv-android#94]
### 问题描述
_通过`http://ip:10481`方式添加自定义直播源，手机端app重启后，反复闪退,无法正常添加_
### 复现步骤
<img width="1050" alt="tv1" src="https://github.com/user-attachments/assets/0bad9852-edd3-48be-a642-d947af8d4ab6">
_如图，这样的操作_

### 预期行为
_mytv-android app dose not crash_

### 系统信息
- IQOO11手机， 
- originOS4系统，
- mytv-Android版本：1.44

### 相关截图或日志
_app反复闪退无法截图，临时：卸载，装回原版_ 。😄

**Comment by yaoxieyoulei** [comment]
要把原来的链接删掉
