### ISSUE TITLE
问题反馈-播放失败

### ISSUE THREAD

**Issue by GGFGG816** [yaoxieyoulei/mytv-android#97]
### 问题描述
使用v1.4.4 播放 rtp流 失败

### 复现步骤
添加自定义直播源 https://iptv.im2k.com/tjuc.m3u （成功，日志中看到成功解析了直播源并且看到了频道列表）
播放任一频道，提示播放失败：ERROR_CODE_IO_NETWORK_CONNECTION_FAILED(2001)

### 预期行为
能够正常播放
（以上节目单和组播地址等均已验证过，同一个设备使用IPTV PRO可以正常播放）

### 系统信息
APP 版本 1.4.4
SONY KD-75X85K 系统版本PGK6.7480.0852CNA
Android TV 10

### 相关截图或日志
无法打开debug日志，以下日志为设置页面复制粘贴。
e
INFO
解析节目单完成，共93个频道
18:06:24
e
ERROR
获取节目单失败
获取远程节目单xml失败，请检查网络连接
18:05:54
c
INFO
解析直播源完成：7个分组，176个频道
18:05:44
h
INFO
服务已启动: 0.0.0.0:10481
18:05:42

**Comment by QoneFeng** [comment]
我的也是这样

**Comment by yaoxieyoulei** [comment]
暂不支持rtp

**Comment by yaoxieyoulei** [comment]
不支持rtp

**Comment by p15proton** [comment]
ava.lang.Exception

**Comment by p15proton** [comment]
java.lang.Exception
