### ISSUE TITLE
V1.4.4 电视版本怎么设置多少直播源

### ISSUE THREAD

**Issue by LL3706** [yaoxieyoulei/mytv-android#98]
### 功能描述
V1.4.4 apk版本怎么设置多少直播源

### 目标
设置多直播源报加载失败

### 解决方案
支持多直播源吗

**Comment by LL3706** [comment]
设置多直播源，格式是分号分隔，还是换行添加就行，换行添加报加载失败

**Comment by LL3706** [comment]
![203fe463092c158527f7c557786cbde](https://github.com/user-attachments/assets/9d3c66e7-179c-42b2-81cc-75c917d23f17)

**Comment by yaoxieyoulei** [comment]
不支持

**Comment by LL3706** [comment]
感谢解答

**Comment by LL3706** [comment]
tv2.2.0 apk 和V1.4.4 apk 这2个版本有啥区别没

**Comment by 5918vo** [comment]
>  tv2.2.0 apk 和V1.4.4 apk 这2个版本有啥区别没
啊 在哪下载的 2.2.0 我怎么看最新只有 1.4.4

**Comment by LL3706** [comment]
> > tv2.2.0 apk 和V1.4.4 apk 这2个版本有啥区别没
> > 啊 在哪下载的 2.2.0 我怎么看最新只有 1.4.4

https://github.com/yaoxieyoulei/mytv-android/releases/tag/tv2.2.0

**Comment by LL3706** [comment]
我的网络不支持ipv6,只能看ipv4的直播源，有可以看到ipv4的直播源吗

**Comment by 5918vo** [comment]
> 我的网络不支持ipv6,只能看ipv4的直播源，有可以看到ipv4的直播源吗

你下载 2.2 之后 有得选，有个 yuanxxx 的直播源
