### ISSUE TITLE
关于使用手机网络与 Wi-Fi 网络下 ipv6 差异

### ISSUE THREAD

**Issue by 5918vo** [yaoxieyoulei/mytv-android#99]
发现在固定的直播源下 Wi-Fi 观看只有 100-200kb 速度，但使用数据网络一般都可以达到 1-2m 速度，请问有没有遇到或解决方法？（Wi-Fi 是电信网络）

**Comment by yaoxieyoulei** [comment]
应该是直播源问题，解决不了

**Comment by 5918vo** [comment]
哦哦 只能这样吧
